export { default as Head } from './Head'
export { default as SEO } from './SEO'
export { default as Footer } from './Footer'
export { default as I18nWidget } from './I18nWidget'
export { default as Navbar } from './Navbar'
export { default as Layout } from './Layout'
export { default as Searchbar } from './Searchbar'
